# Generated by Django 3.2 on 2023-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
