# Generated by Django 3.2 on 2023-01-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_app', '0002_alter_holiday_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
