# Generated by Django 3.2 on 2023-01-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_app', '0003_alter_holiday_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='colour',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
